### ISSUE TITLE
automated visualisation

### ISSUE THREAD

**Issue by tcrundall** [tcrundall/chronostar-tng#30]
Add some kind of visualisation.
@marusazerjal  what do you want to see? :)

**Comment by marusazerjal** [comment]
Components in XY, XU etc., together with the background to see if we missed anything.
While photometry is not an input, it would be useful to add an option to pair the two datasets and plot a CMD to see if members of a component are coeval.

**Comment by tcrundall** [comment]
Do you want to prioritise plotting the final result, or plotting intermediate stages?
Do you want an interactive dashboard using plot.ly or something?

@mikeireland Any particular wishes?

**Comment by tcrundall** [comment]
In order to have plots of intermediate stages, it would be useful to have parameter dumps of those intermediate stages (i.e. weights and components of each converged mixture fit).

Having intermediate parameter dumps is inherently important - lets you check in on "slow" runs, potentially provides restart points for crashed runs, lets you compare final few runs whose BICs only differ slightly.

The question then arises of how to store these parameter dumps. Especially since this will introduce a strong coupling between the directory structure of parameter dumps and any plotting script hoping to plot each dump.

I'll explore this further in a separate issue.

**Comment by tcrundall** [comment]
I'll put off plotting intermediate stages until #36 is completed.

For the current milestone I'll plot final results:
-[ ] Plot all stars, coloured by membership, sized by inverse of component weight, on each feature plane of interest
-[ ] Plot CMD based on Gaia photometry, stars coloured by membership
