### ISSUE TITLE
Add entry point for membership overlap calculation

### ISSUE THREAD

**Issue by tcrundall** [tcrundall/chronostar-tng#63]
Allow users to specify some set of components, and receive as a result relative membership probabilities.

**Comment by tcrundall** [comment]
I’m a bit uncertain how to approach providing a quick entry point for membership overlaps.

The primary source of my uncertainty, is that aged components are parameterised by their birth mean and spread, and their age. There isn’t a simple relationship to go from some arbitrary current-day distribution to a parameterisation of its birth.

But maybe I'm just misremembering, and @mikeireland just wanted a way to calculate membership probabilities given a bunch of chronostar fitted components. Is that right? If so, I'll do that.

**Comment by mikeireland** [comment]
Yes - I just wanted a way to calculate membership probabilities given a bunch of chronostar fitted components. This is what Marusa needed for Sco-Cen.


On 3 Nov 2022, at 3:24 am, Timothy Crundall ***@***.******@***.***>> wrote:



I’m a bit uncertain how to approach providing a quick entry point for membership overlaps.

The primary source of my uncertainty, is that aged components are parameterised by their birth mean and spread, and their age. There isn’t a simple relationship to go from some arbitrary current-day distribution to a parameterisation of its birth.

But maybe I'm just misremembering, and @mikeireland<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmikeireland&data=05%7C01%7Cmichael.ireland%40anu.edu.au%7C7fe0f4f5074b49f6949d08dabceeac3e%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C638030030521763624%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KnbvWuw%2FlwNXYzgcXG7ESeoZ%2BmVis4U8alhXiAAtzjw%3D&reserved=0> just wanted a way to calculate membership probabilities given a bunch of chronostar fitted components. Is that right? If so, I'll do that.

**Comment by tcrundall** [comment]
Perfect. That is done.

Although at the moment all entry points that read in previous results are hardcoded for SphereSpaceTimeComponent. At some point we'll need to describe in the results file - in a computer readable way - which component class each parameter set is describing. But this can be discussed in a different issue: #69
